In [18]:
import tensorflow as tf

In [19]:
a = tf.constant([3,1])
b = tf.constant(2)
x = tf.multiply(a, b)
tf.InteractiveSession()
a.eval()


array([3, 1], dtype=int32)

In [20]:
tf.zeros([2, 3], dtype=tf.int32).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [21]:
c = tf.constant([[1, 2], [3, 4]])
tf.zeros_like(c).eval()

array([[0, 0],
       [0, 0]], dtype=int32)

In [22]:
tf.fill([2, 3], 7).eval()

array([[7, 7, 7],
       [7, 7, 7]], dtype=int32)

In [24]:
tf.linspace(10., 13., 4).eval() #start and stop have to be float

array([ 10.,  11.,  12.,  13.], dtype=float32)

In [25]:
tf.range(3, 18, 3).eval()

array([ 3,  6,  9, 12, 15], dtype=int32)

In [26]:
tf.range(5).eval()

array([0, 1, 2, 3, 4], dtype=int32)

**Tensor objects are not iterable**

for _ in tf.range(3): # TypeError

# Randomly Generated Constants

In [56]:
tf.random_shuffle([[1,2],[3,4],[5,6]]).eval() #shuffle 1st dim

array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)

In [63]:
import numpy as np
a = tf.constant(np.random.normal(size = (3,4)))
a.eval()

array([[ 1.88047182, -1.414999  ,  1.43114785, -1.93555539],
       [-1.5340854 , -2.44692854,  0.46580373,  0.62926114],
       [-0.57761134, -0.34458869, -0.0626049 ,  0.78744068]])

In [67]:
tf.multinomial(a,10).eval()

array([[2, 0, 0, 0, 2, 0, 0, 2, 0, 0],
       [2, 1, 3, 2, 3, 3, 2, 3, 2, 3],
       [3, 3, 3, 3, 3, 3, 3, 0, 3, 3]])

In [68]:
tf.random_gamma([10], 3).eval()

array([ 1.23872662,  1.64838719,  3.02911305,  1.32721353,  3.7495172 ,
        2.66255569,  3.1065979 ,  1.13454103,  4.59409904,  5.21049356], dtype=float32)

In [92]:
tf.set_random_seed(1)
a = tf.random_uniform([1])
print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  # generates 'A1'
  print(sess1.run(a))  # generates 'A2'

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  # generates 'A3'
  print(sess2.run(a))  # generates 'A4'

Session 1
[ 0.59254789]
[ 0.29783189]
Session 2
[ 0.59254789]
[ 0.29783189]
