# Operators

In [49]:
import tensorflow as tf

In [50]:
a = tf.constant([1, 2])
b = tf.constant([3, 4])
tf.InteractiveSession()

In [51]:
tf.add(a, b).eval()

array([4, 6], dtype=int32)

In [52]:
tf.add_n([a, b, b]).eval() #inputs: A list of Tensor objects, each with same shape and type

array([ 7, 10], dtype=int32)

In [53]:
tf.multiply(a, b).eval() #element-wise

array([3, 8], dtype=int32)

In [56]:
c = tf.reshape(a, [1, 2])
d = tf.reshape(b, [2, 1])
print('c=',c.eval())
print('d=',d.eval())
print('c*d=',(c*d).eval())
print('matmul(c,d)=', tf.matmul(c, d).eval())

c= [[1 2]]
d= [[3]
 [4]]
c*d= [[3 6]
 [4 8]]
matmul(c,d)= [[11]]


In [57]:
c = tf.constant([[1, 0], [0, 1]])
d = tf.constant([[1, 2], [3, 4]])
tf.matmul(c, d, transpose_b=True).eval() #input tensors of rank > 2

array([[1, 3],
       [2, 4]], dtype=int32)

In [63]:
tf.div(a, b).eval() #element-wise

array([0, 0], dtype=int32)

In [64]:
tf.mod(a, b).eval()

array([1, 2], dtype=int32)

In [72]:
t = [[True, False], [False, True]]
print(tf.zeros_like(t).eval())
print(tf.ones_like(t).eval())

[[False False]
 [False False]]
[[ True  True]
 [ True  True]]


# Data Types

In [73]:
import numpy as np

In [75]:
tf.int32 == np.int32

True

# Variables

In [86]:
W = tf.Variable([2, 3])
W.assign([1, 10])
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

[2 3]


In [91]:
W = tf.Variable([2, 3])
assign_op = W.assign([1, 10])
with tf.Session() as sess:
#     sess.run(W.initializer)
    sess.run(assign_op)
    print(W.eval())

[ 1 10]


In [106]:
my_var = tf.Variable(2)
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(my_var.eval())
    print(my_var.eval())
    print(sess.run(my_var_times_two))
    print(my_var_times_two.eval())
    print(my_var_times_two.eval())
    print(sess.run(my_var_times_two))


2
2
4
8
16
32


In [109]:
my_var = tf.Variable(10)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(sess.run(my_var.assign_add(10)))
    print(sess.run(my_var.assign_sub(2)))

    

20
18


In [110]:
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(2)))
print(sess2.run(W.assign_sub(2)))



12
8


# Placeholders

In [122]:
a = tf.placeholder(tf.float32, shape=None)
# a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)
c = a + b

list_of_values_for_a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
with tf.Session() as sess:
    for a_value in list_of_values_for_a:
        print(sess.run(c, {a: a_value}))

[ 6.  7.  8.]
[  9.  10.  11.]
[ 12.  13.  14.]


In [129]:
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    replace_dict = {a: 15}
    print(sess.run(b, feed_dict=replace_dict))

45
